# docker compose file for postgres testing in pg admin, see db setup notes
services:
# postgres db service info
  postgres:
    image: postgres:15
    container_name: makerspace-postgres
    restart: always
    environment:
      POSTGRES_USER: app_admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: collab_app
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
# pg admin service and login information
# depends on postgres to ensure it starts correctly
  pgadmin:
    image: dpage/pgadmin4
    container_name: makerspace-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
