CREATE TABLE training_waiver_signatures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    equipment_id BIGINT NOT NULL REFERENCES equipment(id) ON DELETE CASCADE,
    signer_name VARCHAR(200) NOT NULL,
    signed_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_training_waiver_user_equipment UNIQUE (user_id, equipment_id)
);