ALTER TABLE equipment
    ADD COLUMN training_required BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE equipment
SET training_required = TRUE
WHERE category = 'LASER';

CREATE TABLE training_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    equipment_id BIGINT NOT NULL REFERENCES equipment(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    video_completed_at TIMESTAMP,
    completed_at TIMESTAMP,
    CONSTRAINT uk_training_task_user_equipment UNIQUE (user_id, equipment_id)
);

CREATE INDEX idx_training_tasks_user ON training_tasks(user_id, created_at);