# PostgreSQL

spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/collaboratory_makerspace
spring.datasource.username=admin
spring.datasource.password=postgres
spring.security.user.name=user
spring.security.user.password=password

# GitHub Login
#
#spring.security.oauth2.client.registration.github.client-id=Ov23liT64pRJbCnyNP0q
#spring.security.oauth2.client.registration.github.client-secret=e88e057eb6268736cdc498021ed0a57d5828b75c

# Google Login

logging.level.org.springframework.security=TRACE
#spring.security.oauth2.client.registration.google.client-id=846303387091-as0ru06v3q6h38l4sj6240sk0h8tuiur.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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

# Okta Credentials

okta.oauth2.issuer=https://dev-qwnfczazu6lr161q.us.auth0.com/
okta.oauth2.client-id=25gI86kDbccgzawXvVX7s3Fxe21d5oOZ
okta.oauth2.client-secret=--BqIjWccZ43bNe3YBk3idJNgqtCSj9o8pgAq74x5QbZutrIADpZZtPi8RL1yp_f

okta.oauth2.groupsClaim=https://collaboratory.makerspace.com/roles
okta.oauth2.audience=https://dev-qwnfczazu6lr161q.us.auth0.com/api/v2/

app.jwt.secret=L/1Rct2n1IHvtOwcOGwl8c86FeA2mFR8+bKWOCcqCs0=
app.jwt.expiration=3600000