# PostgreSQL

spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/collaboratory_makerspace
spring.datasource.username=admin
spring.datasource.password=postgres
spring.security.user.name=user
spring.security.user.password=password
spring.flyway.baseline-on-migrate=true

# Google Login

logging.level.org.springframework.security=TRACE
spring.security.oauth2.client.registration.google.client-id=846303387091-as0ru06v3q6h38l4sj6240sk0h8tuiur.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}

# Okta Credentials

#okta.oauth2.issuer=https://dev-qwnfczazu6lr161q.us.auth0.com/
#okta.oauth2.client-id=25gI86kDbccgzawXvVX7s3Fxe21d5oOZ
#okta.oauth2.client-secret=${OKTA_OAUTH2_CLIENT_SECRET}

# Microsoft (covers Outlook, Hotmail, Live)
spring.security.oauth2.client.registration.microsoft.client-id=${MICROSOFT_CLIENT_ID}
spring.security.oauth2.client.registration.microsoft.client-secret=${MICROSOFT_CLIENT_SECRET}
spring.security.oauth2.client.registration.microsoft.scope=openid,profile,email
spring.security.oauth2.client.provider.microsoft.issuer-uri=https://login.microsoftonline.com/common/v2.0

# Apple
spring.security.oauth2.client.registration.apple.client-id=${APPLE_CLIENT_ID}
spring.security.oauth2.client.registration.apple.client-secret=${APPLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.apple.scope=openid,name,email
spring.security.oauth2.client.registration.apple.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.apple.authorization-uri=https://appleid.apple.com/auth/authorize
spring.security.oauth2.client.provider.apple.token-uri=https://appleid.apple.com/auth/token
spring.security.oauth2.client.provider.apple.jwk-set-uri=https://appleid.apple.com/auth/keys
spring.security.oauth2.client.provider.apple.user-name-attribute=sub


okta.oauth2.groupsClaim=https://collaboratory.makerspace.com/roles
okta.oauth2.audience=https://dev-qwnfczazu6lr161q.us.auth0.com/api/v2/

app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration=3600000