spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/collaboratory_makerspace
spring.datasource.username=admin
spring.datasource.password=postgres
spring.security.user.name=user
spring.security.user.password=password

# GitHub Login
spring.security.oauth2.client.registration.github.client-id=Ov23liT64pRJbCnyNP0q
spring.security.oauth2.client.registration.github.client-secret=e88e057eb6268736cdc498021ed0a57d5828b75c

# Google Login

logging.level.org.springframework.security=TRACE
spring.security.oauth2.client.registration.google.client-id=60920856758-gbuieu7hgs3v7v7snalvpvj47slbkb1o.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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